#!/usr/bin/env zsh

######################################## EXPORT ENVIRONMENT VARIABLE ########################################

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_PICTURES_DIR="$HOME/Pictures"

# DIRECTORIES
export DOTFILES="$XDG_DATA_HOME/chezmoi"
export HYPRSHOT_DIR="$XDG_PICTURES_DIR/screenshots"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZSH="$ZDOTDIR"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# cargo
if [[ "$(uname)" == "Darwin" ]]; then
    . "$HOME/.cargo/env"
fi
