#!/usr/bin/env zsh

######################################## EXPORT ENVIRONMENT VARIABLE ########################################

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_BIN_HOME="$HOME/.local/bin"

# DIRECTORIES
export DOTFILES="$HOME/.dotfiles"
export HYPRSHOT_DIR="$XDG_PICTURES_DIR/screenshots/hyprshot/"
export CLOUD="$HOME/Cloud"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# go
export GOPATH=$HOME/.go
export GOBIN=$GOPATH/bin

# python
export PYTHONPATH=/usr/lib/python3.12/site-packages:$PYTHONPATH
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init --path)"

# antidote
export ANTIDOTE_HOME=~/.cache/antidote

# brew
export HOMEBREW_NO_ENV_HINTS=true

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
    --highlight-line \
    --info=inline-right \
    --layout=reverse \
    --color=bg+:#283457 \
    --color=bg:#16161e \
    --color=border:#27a1b9 \
    --color=fg:#c0caf5 \
    --color=gutter:#16161e \
    --color=header:#ff9e64 \
    --color=hl+:#2ac3de \
    --color=hl:#2ac3de \
    --color=info:#545c7e \
    --color=marker:#ff007c \
    --color=pointer:#ff007c \
    --color=prompt:#2ac3de \
    --color=query:#c0caf5:regular \
    --color=scrollbar:#27a1b9 \
    --color=separator:#ff9e64 \
    --color=spinner:#ff007c \
"
export FZF_MARKS_FILE="$HOME/.local/share/.fzf-marks"

# from xdg-ninja
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export WINEPREFIX="$XDG_DATA_HOME/wine"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export NVM_DIR="$XDG_DATA_HOME/nvm"

# path
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH:$HOME/.local/bin:$HOME/.cargo/bin:$GOBIN"

# pagers
if [[ "$(uname)" == "Darwin" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export LESSOPEN="| /opt/homebrew/bin/src-hilite-lesspipe.sh %s"
    export LESS='-R '
    export MANPAGER="less -R"
    export PAGER="less -R"
fi

