-- This machine's hardware facts. Generated by chezmoi from
-- .chezmoidata/machines.toml; see machine.lua.tmpl. Branch on the capability
-- flags below, never on hostname, so a new machine is a data entry.
local machine = require("machine")

--- Monitor to pin a window or workspace to, or nil on a machine without a real
--- primary+secondary layout, where naming an output is meaningless.
--- @param output string
--- @return string|nil
local function pin(output)
    return machine.multihead and output or nil
end

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

for _, m in ipairs(machine.monitors) do
    hl.monitor({ output = m.output, mode = m.mode, position = m.position, scale = m.scale, transform = m.transform })
end

---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "ghostty"
local fileManager = "ghostty -e yazi"
local menu        = "rofi -show drun"
local browser     = "zen-browser"
local lockscreen  = "hyprlock"
local pdfViewer   = "zathura"
local noteTaker   = "~/.config/hypr/scripts/notetaker.sh"
local picker      = "~/.config/hypr/scripts/picker.sh"
local soundSheet  = "~/.config/hypr/scripts/soundboard-show.sh"
local bindSheet   = "~/.config/hypr/scripts/binds-show.sh"

-------------------
---- AUTOSTART ----
-------------------

-- Autostart keys that name a program local above. Looking the local up here
-- keeps it the single definition of the command, rather than repeating the
-- string in machines.toml.
local autostartLocals = {
    lockscreen = lockscreen,
}

hl.on("hyprland.start", function()
    for _, key in ipairs(machine.autostart) do
        hl.exec_cmd(autostartLocals[key] or machine.commands[key])
    end
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")
if machine.vaapi then
    hl.env("LIBVA_DRIVER_NAME", machine.vaapi)
end
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("XDG_DATA_DIRS", "/var/lib/flatpak/exports/share:" .. os.getenv("HOME") .. "/.local/share/flatpak/exports/share:" .. "/usr/local/share:/usr/share")
-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 3,
        gaps_out = 8,

        border_size = 2,

        col = {
            active_border   = "rgba(f7768eff)",
            inactive_border = "rgba(565f89cc)",
        },

        resize_on_border = true,
        allow_tearing    = true,

        layout = "dwindle",
    },

    decoration = {
        rounding = 10,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },

        blur = {
            enabled           = true,
            size              = 6,
            passes            = 3,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = false,

            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper   = 0,
        disable_hyprland_logo     = true,
        on_focus_under_fullscreen = 2,
        focus_on_activate         = false,
    },

    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "ctrl:nocaps",
        kb_rules   = "",

        follow_mouse  = 1,
        mouse_refocus = false,

        sensitivity = -0.25, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },

    cursor = {
        hide_on_key_press = true,
    },
})

-- The Voyager handles its own layout, so keep a real Caps Lock there.
for _, name in ipairs({ "zsa-technology-labs-voyager", "zsa-technology-labs-voyager-keyboard" }) do
    hl.device({ name = name, kb_options = "caps:capslock" })
end

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",     enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 7,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",      enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8,  bezier = "default" })
hl.animation({ leaf = "fade",        enabled = true, speed = 7,  bezier = "default" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 6,  bezier = "default" })

---------------------
---- KEYBINDINGS ----
---------------------

-- Every bind meant for a human carries a "Group: what it does" description, which
-- the SUPER + / sheet reads back out of `hyprctl binds`. The sheet lists groups in
-- the order they first appear here and binds in the order they are written, so
-- this section is kept sorted by how often a bind is reached for -- everyday at
-- the top, niche at the bottom. Consecutive binds in a group that share a
-- description are shown as one row. A bind with no description stays off the
-- sheet (the soundboard has its own).

local mainMod = "SUPER"

--- @param text string "Group: what it does"
--- @return table
local function desc(text)
    return { description = text }
end

-- Apps
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu),        desc("Apps: Launcher"))
hl.bind(mainMod .. " + E",     hl.dsp.exec_cmd(fileManager), desc("Apps: File manager"))
hl.bind(mainMod .. " + Z",     hl.dsp.exec_cmd(pdfViewer),   desc("Apps: PDF viewer"))
hl.bind(mainMod .. " + N",     hl.dsp.exec_cmd(noteTaker),   desc("Apps: Quick note"))
hl.bind(mainMod .. " + Q",     hl.dsp.exec_cmd("qimgv"),     desc("Apps: Image viewer"))
hl.bind(mainMod .. " + A",     hl.dsp.exec_cmd("nwg-drawer -nofs -ovl -wm hyprland -k -c 8 -is 64 -spacing 16"), desc("Apps: App drawer"))

-- Named workspaces: the letter goes there, SHIFT + the letter sends the window
-- there. Each one spawns its app when first opened empty (see workspace rules), so
-- a second instance is a job for the launcher.
local named = {
    { key = "T", ws = 20, name = "terminal" },
    { key = "B", ws = 30, name = "browser" },
    { key = "D", ws = 40, name = "Discord" },
    { key = "S", ws = 50, name = "Steam" },
    { key = "M", ws = 60, name = "mail" },
    { key = "O", ws = 70, name = "Obsidian" },
    { key = "G", ws = 100, name = "games" },
}
for _, n in ipairs(named) do
    hl.bind(mainMod .. " + " .. n.key, hl.dsp.focus({ workspace = n.ws }),
        desc("Named workspaces: Go to " .. n.name .. " (" .. n.ws .. ")"))
    hl.bind(mainMod .. " + SHIFT + " .. n.key, hl.dsp.window.move({ workspace = n.ws }),
        desc("Named workspaces: Move window to " .. n.name))
end

-- Windows
hl.bind(mainMod .. " + C",             hl.dsp.window.close(),                             desc("Windows: Close"))
hl.bind(mainMod .. " + H",             hl.dsp.focus({ direction = "l" }),                 desc("Windows: Focus left/right/up/down"))
hl.bind(mainMod .. " + L",             hl.dsp.focus({ direction = "r" }),                 desc("Windows: Focus left/right/up/down"))
hl.bind(mainMod .. " + K",             hl.dsp.focus({ direction = "u" }),                 desc("Windows: Focus left/right/up/down"))
hl.bind(mainMod .. " + J",             hl.dsp.focus({ direction = "d" }),                 desc("Windows: Focus left/right/up/down"))
hl.bind(mainMod .. " + SHIFT + H",     hl.dsp.window.move({ direction = "l" }),           desc("Windows: Move left/right/up/down"))
hl.bind(mainMod .. " + SHIFT + L",     hl.dsp.window.move({ direction = "r" }),           desc("Windows: Move left/right/up/down"))
hl.bind(mainMod .. " + SHIFT + K",     hl.dsp.window.move({ direction = "u" }),           desc("Windows: Move left/right/up/down"))
hl.bind(mainMod .. " + SHIFT + J",     hl.dsp.window.move({ direction = "d" }),           desc("Windows: Move left/right/up/down"))
-- ALT + Tab remake but only works inside workspace
hl.bind(mainMod .. " + Tab",           hl.dsp.window.cycle_next(),                        desc("Windows: Cycle in workspace"))
hl.bind(mainMod .. " + Tab",           hl.dsp.window.bring_to_top())
hl.bind(mainMod .. " + V",             hl.dsp.window.float(),                             desc("Windows: Toggle floating"))
hl.bind(mainMod .. " + HOME",          hl.dsp.window.fullscreen({ mode = "maximized" }),  desc("Windows: Maximize"))
hl.bind(mainMod .. " + SHIFT + HOME",  hl.dsp.window.fullscreen({ mode = "fullscreen" }), desc("Windows: Fullscreen"))
-- Toggle split orientation: side-by-side <-> top/bottom
hl.bind(mainMod .. " + SHIFT + SPACE", hl.dsp.layout("togglesplit"),                      desc("Windows: Toggle split direction"))
hl.bind(mainMod .. " + mouse:272",     hl.dsp.window.drag(),   { mouse = true, description = "Windows: Drag to move" })
hl.bind(mainMod .. " + mouse:273",     hl.dsp.window.resize(), { mouse = true, description = "Windows: Drag to resize" })

-- Numbered workspaces 1-10, and the special (scratchpad) one. Two loops rather
-- than one, so each set is a consecutive run the sheet can collapse to a row.
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }), desc("Workspaces: Go to workspace 1-10"))
end
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }), desc("Workspaces: Move window to 1-10"))
end

hl.bind(mainMod .. " + minus",         hl.dsp.workspace.toggle_special("magic"),            desc("Workspaces: Toggle scratchpad"))
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.window.move({ workspace = "special:magic" }), desc("Workspaces: Move window to scratchpad"))

-- Media (mpc)
hl.bind(mainMod .. " + ALT + SPACE", hl.dsp.exec_cmd("mpc toggle"),    desc("Media: Play/pause"))
hl.bind(mainMod .. " + RIGHT",       hl.dsp.exec_cmd("mpc next"),      desc("Media: Next track"))
hl.bind(mainMod .. " + LEFT",        hl.dsp.exec_cmd("mpc prev"),      desc("Media: Previous track"))
hl.bind(mainMod .. " + UP",          hl.dsp.exec_cmd("mpc volume +5"), desc("Media: Volume up"))
hl.bind(mainMod .. " + DOWN",        hl.dsp.exec_cmd("mpc volume -5"), desc("Media: Volume down"))

-- Picker
hl.bind(mainMod .. " + P",                  hl.dsp.exec_cmd(picker),                  desc("Pickers: All pickers"))
hl.bind(mainMod .. " + SHIFT + C",          hl.dsp.exec_cmd(picker .. " clipboard"),  desc("Pickers: Clipboard history"))
hl.bind(mainMod .. " + SHIFT + P",          hl.dsp.exec_cmd(picker .. " playlist"),   desc("Pickers: Playlist"))
hl.bind(mainMod .. " + SHIFT + N",          hl.dsp.exec_cmd(picker .. " note"),       desc("Pickers: Notes"))
hl.bind(mainMod .. " + SHIFT + W",          hl.dsp.exec_cmd(picker .. " wallpaper"),  desc("Pickers: Wallpaper"))
hl.bind(mainMod .. " + SHIFT + apostrophe", hl.dsp.exec_cmd(picker .. " soundboard"), desc("Pickers: Play any sound"))

-- Hyprshot
hl.bind("PRINT",                       hl.dsp.exec_cmd("hyprshot -m output"), desc("Screenshots: Whole monitor"))
hl.bind(mainMod .. " + PRINT",         hl.dsp.exec_cmd("hyprshot -m window"), desc("Screenshots: Window"))
hl.bind(mainMod .. " + SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m region"), desc("Screenshots: Region"))

require("soundboard").setup(mainMod)

-- Cheat sheets: this section, and the soundboard banks drawn from the same tables.
hl.bind(mainMod .. " + slash",         hl.dsp.exec_cmd(bindSheet),  desc("Help: Keybinds"))
hl.bind(mainMod .. " + SHIFT + slash", hl.dsp.exec_cmd(soundSheet), desc("Help: Soundboard"))
hl.bind(mainMod .. " + SHIFT + PAUSE", hl.dsp.exec_cmd(lockscreen), desc("Session: Lock screen"))

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Neovide
hl.window_rule({
    name  = "neovide",
    match = { class = "neovide" },

    monitor = pin(machine.primary),
    float   = true,
    size    = { 1920, 1080 },
})

-- Notetaker capture
hl.window_rule({
    name  = "notetaker",
    match = { title = "^(Notetaker)$" },

    float  = true,
    center = true,
    size   = { 1000, 700 },
})

-- Mega
hl.window_rule({
    name  = "mega",
    match = { class = "MEGA" },

    float            = true,
    render_unfocused = true,
})

-- Zoom
hl.window_rule({
    name  = "zoom-menu",
    match = { class = "zoom", initial_title = "(menu window)" },

    stay_focused = true,
})

-- Discord
hl.window_rule({
    name  = "discord",
    match = { class = "discord" },

    workspace = "40",
    monitor   = pin(machine.secondary),
})

-- Steam Client
hl.window_rule({
    name  = "steam-main",
    match = { class = "^(steam)$" },

    workspace = "50",
    monitor   = pin(machine.primary),
})

-- Steam - Subwindows (everything except main Steam window)
hl.window_rule({
    name  = "steam-subwindows",
    match = { class = "^(steam)$", title = "negative:^Steam$" },

    float = true,
})

-- Steam - Known Popup/Dialog Bugs
hl.window_rule({
    name  = "steam-popups",
    match = { class = "^(steam)$", title = "^()$" },

    min_size = { 1, 1 },
})

-- Steam Games
-- gametrak writes $game_regex into games.conf in the old hyprlang format; read it
-- back out here since Lua configs have no `source` keyword.
local function game_regex(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local contents = f:read("a")
    f:close()
    return contents:match("%$game_regex%s*=%s*([^\n]+)")
end

if machine.gametrak then
    local games = game_regex(os.getenv("HOME") .. "/.config/gametrak/games.conf")
    if games then
        hl.window_rule({
            name  = "steam-games",
            match = { class = games },

            workspace    = "100",
            monitor      = pin(machine.primary),
            fullscreen   = true,
            immediate    = true,
            idle_inhibit = "always",
        })
    end
end

-- GIMP
hl.window_rule({
    name  = "gimp-dialogs",
    match = { class = "^(script-fu|file-.*)$" },
    float = true,
})

hl.window_rule({
    name  = "gimp-preferences",
    match = { class = "^(org\\.gimp\\.GIMP)$", title = "^(Preferences)$" },
    float = true,
})

-- XDG Desktop Portal
hl.window_rule({
    name  = "xdg-portal",
    match = { class = "^(xdg-desktop-portal-gtk)$" },
    float = true,
})

-- GODOT Engine Test Window
hl.window_rule({
    name  = "godot-runner",
    match = { title = ".*DEBUG.*" },
    float = true,
})

-- Default
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

-- See https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

if machine.multihead then
    -- Workspaces 1-10 are pinned across the pair: 1 on primary, the rest on
    -- secondary. A single display deliberately gets none of these -- pinning
    -- workspace 1 default+persistent to an output that does not exist is what
    -- leaves a lone screen with no usable workspace at login, and Hyprland's
    -- own defaults are already correct there.
    hl.workspace_rule({ workspace = "1", monitor = machine.primary, default = true, persistent = true })
    hl.workspace_rule({ workspace = "2", monitor = machine.secondary, persistent = true })
    hl.workspace_rule({ workspace = "3", monitor = machine.secondary })
    hl.workspace_rule({ workspace = "4", monitor = machine.secondary })
    hl.workspace_rule({ workspace = "5", monitor = machine.secondary })
    hl.workspace_rule({ workspace = "6", monitor = machine.secondary })
    hl.workspace_rule({ workspace = "7", monitor = machine.secondary })
    hl.workspace_rule({ workspace = "8", monitor = machine.secondary, on_created_empty = "ticktick" })
    hl.workspace_rule({ workspace = "9", monitor = machine.secondary, on_created_empty = "spotify" })
    hl.workspace_rule({ workspace = "10", monitor = machine.secondary })
end

-- Named launcher workspaces. pin() collapses to nil on a single display, so
-- these carry no monitor there and stay safe.
hl.workspace_rule({ workspace = "20", monitor = pin(machine.primary), on_created_empty = terminal })
hl.workspace_rule({ workspace = "30", monitor = pin(machine.secondary), on_created_empty = browser })
hl.workspace_rule({ workspace = "50", monitor = pin(machine.primary), on_created_empty = "gtk-launch steam" })

if machine.multihead then
    hl.workspace_rule({ workspace = "40", monitor = machine.secondary, on_created_empty = "gtk-launch discord" })
    hl.workspace_rule({ workspace = "60", monitor = machine.secondary, on_created_empty = "gtk-launch com.fastmail.Fastmail" })
    hl.workspace_rule({ workspace = "70", monitor = machine.secondary, on_created_empty = "obsidian" })
end

hl.workspace_rule({
    workspace   = "100",
    monitor     = pin(machine.primary),
    gaps_in     = 0,
    gaps_out    = 0,
    no_border   = true,
    no_rounding = true,
})
