source = ~/.config/hypr/hyprpaper-wallpaper.conf

wallpaper {
    monitor = HDMI-A-1
    path = $wallpaper_top
    fit_mode = stretch
}
wallpaper {
    monitor = DP-2
    path = $wallpaper_bottom
    fit_mode = stretch
}

# Disable IPC
ipc = off

splash = false
