"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark = "tokyo-night"
light = "tokyo-night"

[icon]
append_dirs = [
    { name = "Archive", text = "" },
    { name = "Cloud", text = "" },
    { name = "Dev", text = "" },
    { name = "Notes", text = "" },
]
