#!/usr/bin/env zsh

# +------+
# | OPTS |
# +------+
setopt AUTO_CD            # Go to folder path without using cd.
setopt AUTO_PUSHD         # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS  # Do not store duplicates in the stack.
setopt PUSHD_SILENT       # Do not print the directory stack after pushd or popd.
setopt AUTO_MENU          # show completion menu on succesive tab presses
setopt COMPLETE_IN_WORD   # cd /ho/sco/tm<TAB> expands to /home/scott/tmp
setopt CDABLE_VARS        # Change directory to a path stored in a variable
setopt EXTENDED_GLOB      # Use extended globbing syntax
unsetopt CORRECT_ALL      # Try to correct the spelling of all arguments in a line

# +---------+
# | HISTORY |
# +---------+
setopt EXTENDED_HISTORY       # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY          # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS       # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS   # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS      # Do not display a previously found event.
setopt HIST_IGNORE_SPACE      # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS      # Do not write a duplicate event to the history file.
setopt HIST_VERIFY            # Do not execute immediately upon history expansion.

# +------+
# | PATH |
# +------+
typeset -U path

# +---------+
# | ALIASES |
# +---------+
source "$ZDOTDIR/extras/aliases"

# +---------+
# | SCRIPTS |
# +---------+
source "$ZDOTDIR/extras/scripts.zsh"

# +-----------+
# | VI KEYMAP |
# +-----------+
bindkey -v
export KEYTIMEOUT=1

# # Add Vi text-objects for brackets and quotes
# autoload -Uz select-bracketed select-quoted
# zle -N select-quoted
# zle -N select-bracketed
# for km in viopp visual; do
#     bindkey -M $km -- '-' vi-up-line-or-history
#     for c in {a,i}${(s..)^:-\'\"\`\|,./:;=+@}; do
#         bindkey -M $km $c select-quoted
#     done
#     for c in {a,i}${(s..)^:-'()[]{}<>bB'}; do
#         bindkey -M $km $c select-bracketed
#     done
# done
#
# # Emulation of vim-surround
# autoload -Uz surround
# zle -N delete-surround surround
# zle -N add-surround surround
# zle -N change-surround surround
# bindkey -M vicmd cs change-surround
# bindkey -M vicmd ds delete-surround
# bindkey -M vicmd ys add-surround
# bindkey -M visual S add-surround
#
# # Increment a number
# autoload -Uz incarg
# zle -N incarg
# bindkey -M vicmd '^a' incarg

# +----------------+
# | TAB COMPLETION |
# +----------------+
autoload -Uz compinit
if [[ -n "${ZDOTDIR}/.zcompdump"(#qN.mh+24) ]]; then
    compinit;
else
    compinit -C;
fi;
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&'

# +-----+
# | FZF |
# +-----+
source <(fzf --zsh)

# +----------+
# | Antidote |
# +----------+
source "$ZDOTDIR/.antidote/antidote.zsh"
antidote load

# +--------+
# | PROMPT |
# +--------+
autoload -Uz promptinit && promptinit && prompt pure

# +--------+
# | ZOXIDE |
# +--------+
eval "$(zoxide init zsh)"

# +---------+
# | BINDING |
# +---------+
bindkey -M viins 'jk' vi-cmd-mode

bindkey -r '^l'
bindkey -r '^g'
bindkey -r '^p'

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd '^v' edit-command-line

bindkey '^f' autosuggest-accept
bindkey ' ' magic-space

# +--------------------------+
# | Startup (keep at bottom) |
# +--------------------------+
if [[ -z $TMUX && $TERM == "xterm-kitty" && -z $NEOVIDE ]]; then
    tmux attach-session || tmux;
fi
