#!/usr/bin/env zsh

# +-----------+
# | PROFILING |
# +-----------+
zmodload zsh/zprof

# +------+
# | OPTS |
# +------+
setopt AUTO_CD           # Go to folder path without using cd.
setopt AUTO_PUSHD        # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS # Do not store duplicates in the stack.
setopt PUSHD_SILENT      # Do not print the directory stack after pushd or popd.
setopt AUTO_MENU         # show completion menu on succesive tab presses
setopt COMPLETE_IN_WORD  # cd /ho/sco/tm<TAB> expands to /home/scott/tmp
setopt CDABLE_VARS       # Change directory to a path stored in a variable
setopt EXTENDED_GLOB     # Use extended globbing syntax
unsetopt CORRECT_ALL     # Try to correct the spelling of all arguments in a line

# +---------+
# | HISTORY |
# +---------+
setopt EXTENDED_HISTORY       # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY          # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS       # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS   # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS      # Do not display a previously found event.
setopt HIST_IGNORE_SPACE      # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS      # Do not write a duplicate event to the history file.
setopt HIST_VERIFY            # Do not execute immediately upon history expansion.

# +------+
# | PATH |
# +------+
typeset -U path

# +---------+
# | ZSTYLES |
# +---------+
source "$ZDOTDIR/extras/zstyles"

# +-------+
# | FPATH |
# +-------+
if [[ "$(uname)" = "Darwin" ]]; then
    fpath+=($(brew --prefix)/share/zsh/site-functions)
fi

# +---------+
# | ALIASES |
# +---------+
source "$ZDOTDIR/extras/aliases"

# +---------+
# | SCRIPTS |
# +---------+
source "$ZDOTDIR/extras/scripts.zsh"

# +-----+
# | FZF |
# +-----+
source <(fzf --zsh)

# +----------+
# | Antidote |
# +----------+
source "$ZDOTDIR/.antidote/antidote.zsh"
antidote load

# +--------+
# | PROMPT |
# +--------+
autoload -Uz promptinit && promptinit && prompt pure

# +--------+
# | ZOXIDE |
# +--------+
eval "$(zoxide init zsh)"

# +---------+
# | BINDING |
# +---------+
export KEYTIMEOUT=40
bindkey -r '^l'
bindkey -r '^g'
bindkey -r '^p'
bindkey '^f' autosuggest-accept
bindkey ' ' magic-space

# +--------------------------+
# | Startup (keep at bottom) |
# +--------------------------+
if [[ -z $TMUX && -z $NEOVIDE ]]; then
    tmux attach-session || tmux;
fi
