#!/usr/bin/env zsh

######################################## INITIAL SETUP ########################################

# brew
if [[ "$(uname)" == "Darwin" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export LESSOPEN="| /opt/homebrew/bin/src-hilite-lesspipe.sh %s"
    export LESS=' -R '
fi

# nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# gcloud
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi
if [ -f "/etc/profile.d/google-cloud-cli.sh" ]; then . "/etc/profile.d/google-cloud-cli.sh"; fi

# cargo
if [[ "$(uname)" == "Darwin" ]]; then
    . "$HOME/.cargo/env"
fi

# hyprland
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    exec Hyprland
fi
