#!/usr/bin/env zsh

# +-------------+
# | PRE BINDING |
# +-------------+
bindkey -v

bindkey -M viins 'jk' vi-cmd-mode

bindkey -r '^l'
bindkey -r '^g'
bindkey -r '^p'

# +------+
# | OPTS |
# +------+
unsetopt correct_all
setopt CDABLE_VARS
setopt EXTENDED_GLOB
export BLOCK_SIZE="'1"

# +------+
# | PATH |
# +------+
typeset -U path

# +----------------+
# | TAB COMPLETION |
# +----------------+
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
    compinit;
else
    compinit -C;
fi;
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
setopt complete_in_word         # cd /ho/sco/tm<TAB> expands to /home/scott/tmp
setopt auto_menu                # show completion menu on succesive tab presses
setopt autocd                   # cd to a folder just by typing it's name
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&'

# +---------+
# | ALIASES |
# +---------+
source $ZDOTDIR/extras/aliases

# *-----*
# | FZF |
# *-----*
source <(fzf --zsh)

# +----------+
# | Antidote |
# +----------+
source $ZDOTDIR/.antidote/antidote.zsh 
antidote load

# +--------+
# | PROMPT |
# +--------+
autoload -Uz promptinit && promptinit && prompt pure

# +----------------+
# | CUSTOM SCRIPTS |
# +----------------+
# source $ZDOTDIR/extras/custom-scripts/jump.zsh
source $ZDOTDIR/extras/custom-scripts/jd.zsh
source $ZDOTDIR/extras/custom-scripts/reload_aliases.zsh
source $ZDOTDIR/extras/custom-scripts/y.zsh
source $ZDOTDIR/extras/custom-scripts/vault_backup.zsh

# +---------+
# | Startup |
# +---------+
if [[ -z $TMUX && $TERM == "xterm-kitty" && -z $NEOVIDE ]]; then
    tmux attach-session;
fi

# +--------------+
# | POST BINDING |
# +--------------+
bindkey '^f' autosuggest-accept
bindkey ' ' magic-space

# *------------------------*
# | GOOGLE CLOUD SDK SETUP |
# *------------------------*
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/austingause/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/austingause/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/austingause/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/austingause/google-cloud-sdk/completion.zsh.inc'; fi
